spring.application.name=RestAPI
spring.datasource.url=jdbc:postgresql://localhost:5433/social_media_app
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
server.port=8081
